create table task
(
    id          integer generated by default as identity
        primary key,
    token_id    integer     not null
        references token,
    task        varchar(36) not null,
    date_create timestamp,
    date_update timestamp
);

alter table task
    owner to postgres;

create index ix_task_token_id
    on task (token_id);

