create table token
(
    id          integer generated by default as identity
        primary key,
    user_id     integer     not null,
    token       varchar(36) not null,
    date_create timestamp,
    date_update timestamp
);

alter table token
    owner to postgres;

create index ix_token_user_id
    on token (user_id);

