// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: billing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountId      int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ReservedTokens int64                  `protobuf:"varint,2,opt,name=reserved_tokens,json=reservedTokens,proto3" json:"reserved_tokens,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateTaskRequest) GetReservedTokens() int64 {
	if x != nil {
		return x.ReservedTokens
	}
	return 0
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CloseTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ClosedTokens  int64                  `protobuf:"varint,2,opt,name=closed_tokens,json=closedTokens,proto3" json:"closed_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTaskRequest) Reset() {
	*x = CloseTaskRequest{}
	mi := &file_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTaskRequest) ProtoMessage() {}

func (x *CloseTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTaskRequest.ProtoReflect.Descriptor instead.
func (*CloseTaskRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{2}
}

func (x *CloseTaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CloseTaskRequest) GetClosedTokens() int64 {
	if x != nil {
		return x.ClosedTokens
	}
	return 0
}

type CloseTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTaskResponse) Reset() {
	*x = CloseTaskResponse{}
	mi := &file_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTaskResponse) ProtoMessage() {}

func (x *CloseTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTaskResponse.ProtoReflect.Descriptor instead.
func (*CloseTaskResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{3}
}

var File_billing_proto protoreflect.FileDescriptor

const file_billing_proto_rawDesc = "" +
	"\n" +
	"\rbilling.proto\x12\abilling\"[\n" +
	"\x11CreateTaskRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12'\n" +
	"\x0freserved_tokens\x18\x02 \x01(\x03R\x0ereservedTokens\"*\n" +
	"\x12CreateTaskResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"N\n" +
	"\x11CloseTaskRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rclosed_tokens\x18\x02 \x01(\x03R\fclosedTokens\"\x14\n" +
	"\x12CloseTaskResponse2\x9b\x01\n" +
	"\vTaskService\x12E\n" +
	"\n" +
	"CreateTask\x12\x1a.billing.CreateTaskRequest\x1a\x1b.billing.CreateTaskResponse\x12E\n" +
	"\n" +
	"CloseTask\x12\x1a.billing.CloseTaskRequest\x1a\x1b.billing.CloseTaskResponseB-Z+my-voice-billing/internal/transport/grpc/pbb\x06proto3"

var (
	file_billing_proto_rawDescOnce sync.Once
	file_billing_proto_rawDescData []byte
)

func file_billing_proto_rawDescGZIP() []byte {
	file_billing_proto_rawDescOnce.Do(func() {
		file_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)))
	})
	return file_billing_proto_rawDescData
}

var file_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_billing_proto_goTypes = []any{
	(*CreateTaskRequest)(nil),  // 0: billing.CreateTaskRequest
	(*CreateTaskResponse)(nil), // 1: billing.CreateTaskResponse
	(*CloseTaskRequest)(nil),   // 2: billing.CloseTaskRequest
	(*CloseTaskResponse)(nil),  // 3: billing.CloseTaskResponse
}
var file_billing_proto_depIdxs = []int32{
	0, // 0: billing.TaskService.CreateTask:input_type -> billing.CreateTaskRequest
	2, // 1: billing.TaskService.CloseTask:input_type -> billing.CloseTaskRequest
	1, // 2: billing.TaskService.CreateTask:output_type -> billing.CreateTaskResponse
	3, // 3: billing.TaskService.CloseTask:output_type -> billing.CloseTaskResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_proto_init() }
func file_billing_proto_init() {
	if File_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_proto_goTypes,
		DependencyIndexes: file_billing_proto_depIdxs,
		MessageInfos:      file_billing_proto_msgTypes,
	}.Build()
	File_billing_proto = out.File
	file_billing_proto_goTypes = nil
	file_billing_proto_depIdxs = nil
}

